version: '3.1'

networks:
  web:
    external: true

services:
  jasonkumpf:
    build: .
    image: kumpfjn/serve:latest
    container_name: jasonkumpf
    restart: always
    environment:
      - API_BASE_URL=http://jasonkumpfapi:8088
    volumes:
      - ./dist:/code
    labels:
      - "traefik.backend=jasonkumpf"
      - "traefik.domain=jasonkumpf.com"
      - "traefik.frontend.rule=Host:jasonkumpf.com"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.docker.network=web"
      - "traefik.port=5000"
    networks:
      - web
