version: '3.1'

networks:
  web:
    external: true

services:
  jasonkumpfapidev:
    build: .
    container_name: jasonkumpfapidev
    restart: always
    ports:
      - 8088:8088
    environment:
      - SERVER_PORT=:8088
      - SERVER_HOST=http://localhost
      - PHOTOS_PATH=/photos
    volumes:
      - ./client/static/photos:/photos
    labels:
      - "traefik.enable=false"
    networks:
      - web

